---
openapi: 3.0.3
info:
  title: geo-api
  version: 1.0.0
servers: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
security:
- ApiKeyAuth: []
paths:
  "/api/v1/geolocations":
    get:
      summary: index
      tags:
      - API::V1::Geolocation
      parameters:
      - name: ip_or_host
        in: query
        required: false
        schema:
          type: string
        example: google.com
      responses:
        '200':
          description: returns paginated results with links
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        attributes:
                          type: object
                          properties:
                            ip:
                              type: string
                            host:
                              type: string
                            country:
                              type: string
                            city:
                              type: string
                            latitude:
                              type: string
                            longitude:
                              type: string
                            provider:
                              type: string
                          required:
                          - ip
                          - host
                          - country
                          - city
                          - latitude
                          - longitude
                          - provider
                      required:
                      - id
                      - type
                      - attributes
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                      last:
                        type: string
                      prev:
                        nullable: true
                      next:
                        nullable: true
                        type: string
                    required:
                    - first
                    - last
                    - prev
                    - next
                required:
                - data
                - links
              example:
                data:
                - id: '994'
                  type: geolocation
                  attributes:
                    ip: 28.91.254.135
                    host: google.com
                    country: Zambia
                    city: Tonibury
                    latitude: "-38.64738555986241"
                    longitude: '140.991618230577'
                    provider: IPSTACK
                - id: '995'
                  type: geolocation
                  attributes:
                    ip: 114.139.8.21
                    host: google.com
                    country: Nigeria
                    city: Elanafort
                    latitude: "-66.46296516929172"
                    longitude: "-47.08002537325848"
                    provider: IPSTACK
                - id: '996'
                  type: geolocation
                  attributes:
                    ip: 149.183.169.101
                    host: google.com
                    country: Cocos (Keeling) Islands
                    city: Lake Caterinaton
                    latitude: '69.23587116135542'
                    longitude: '58.12277384115543'
                    provider: IPSTACK
                - id: '997'
                  type: geolocation
                  attributes:
                    ip: 83.220.229.15
                    host: google.com
                    country: United Arab Emirates
                    city: South Doyleside
                    latitude: '69.69859367345765'
                    longitude: '93.87812222881797'
                    provider: IPSTACK
                - id: '998'
                  type: geolocation
                  attributes:
                    ip: 63.142.230.216
                    host: google.com
                    country: Serbia
                    city: Yolandabury
                    latitude: "-46.84629508766217"
                    longitude: "-91.5178692114715"
                    provider: IPSTACK
                links:
                  first: "/api/v1/geolocations?ip_or_host=google.com&page%5Bpage%5D=1&page%5Blimit%5D=5"
                  last: "/api/v1/geolocations?ip_or_host=google.com&page%5Bpage%5D=2&page%5Blimit%5D=5"
                  prev:
                  next: "/api/v1/geolocations?ip_or_host=google.com&page%5Bpage%5D=2&page%5Blimit%5D=5"
        '400':
          description: returns 400 bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                      required:
                      - message
                required:
                - errors
              example:
                errors:
                - message: Query parameter is required (should be IP or Host)
    post:
      summary: create
      tags:
      - API::V1::Geolocation
      responses:
        '201':
          description: returns success and creates new geolocation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          ip:
                            type: string
                          host:
                            type: string
                          country:
                            type: string
                          city:
                            type: string
                          latitude:
                            type: string
                          longitude:
                            type: string
                          provider:
                            type: string
                        required:
                        - ip
                        - host
                        - country
                        - city
                        - latitude
                        - longitude
                        - provider
                    required:
                    - id
                    - type
                    - attributes
                required:
                - data
              example:
                data:
                  id: '962'
                  type: geolocation
                  attributes:
                    ip: 218.149.132.112
                    host: google.com
                    country: United States
                    city: Chicago
                    latitude: '10.0'
                    longitude: '11.1'
                    provider: IPSTACK
        '400':
          description: returns unprocessable entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        ip:
                          type: array
                          items:
                            type: string
                        country:
                          type: array
                          items:
                            type: string
                        city:
                          type: array
                          items:
                            type: string
                        latitude:
                          type: array
                          items:
                            type: string
                        longitude:
                          type: array
                          items:
                            type: string
                      required:
                      - ip
                      - country
                      - city
                      - latitude
                      - longitude
                required:
                - errors
              example:
                errors:
                - ip:
                  - must be a valid IPv4 or IPv6 address
                  country:
                  - can't be blank
                  city:
                  - can't be blank
                  latitude:
                  - can't be blank
                  longitude:
                  - can't be blank
        '422':
          description: returns successfully list of resources
          content:
            application/json:
              schema:
                type: object
                properties: {}
                required:
                - errors
              example: {}
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                geolocation:
                  type: object
                  properties:
                    ip_or_host:
                      type: string
                  required:
                  - ip_or_host
              required:
              - geolocation
            example:
              geolocation:
                ip_or_host: 136.100.184.202
          application/json:
            schema:
              type: object
              properties:
                geolocation:
                  type: object
                  properties:
                    ip_or_host:
                      type: string
                  required:
                  - ip_or_host
              required:
              - geolocation
            example:
              geolocation:
                ip_or_host: google.com
  "/api/v1/geolocations/{id}":
    delete:
      summary: destroy
      tags:
      - API::V1::Geolocation
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 1004
      responses:
        '204':
          description: returns no content and destroys geolocation
        '404':
          description: returns 404 not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                      required:
                      - message
                required:
                - errors
              example:
                errors:
                - message: Resource not found
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties: {}
            example: {}
          application/json:
            schema:
              type: object
              properties: {}
            example: {}
    get:
      summary: show
      tags:
      - API::V1::Geolocation
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        example: dummy
      responses:
        '200':
          description: returns successfully single resource
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          ip:
                            type: string
                          host:
                            type: string
                          country:
                            type: string
                          city:
                            type: string
                          latitude:
                            type: string
                          longitude:
                            type: string
                          provider:
                            type: string
                        required:
                        - ip
                        - host
                        - country
                        - city
                        - latitude
                        - longitude
                        - provider
                    required:
                    - id
                    - type
                    - attributes
                required:
                - data
              example:
                data:
                  id: '963'
                  type: geolocation
                  attributes:
                    ip: 171.2.197.145
                    host: http://barton.test/jenniffer
                    country: Canada
                    city: North Renaldomouth
                    latitude: "-11.71209762277966"
                    longitude: "-19.50387504887032"
                    provider: IPSTACK
        '404':
          description: returns 404 not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                      required:
                      - message
                required:
                - errors
              example:
                errors:
                - message: Resource not found
