---
openapi: 3.0.3
info:
  title: geo-api
  version: 1.0.0
servers: []
paths:
  "/api/v1/geolocations":
    get:
      summary: index
      tags:
      - API::V1::Geolocation
      parameters:
      - name: ip_or_host
        in: query
        required: false
        schema:
          type: string
        example: google.com
      responses:
        '200':
          description: returns paginated results with links
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        attributes:
                          type: object
                          properties:
                            ip:
                              type: string
                            country:
                              type: string
                            city:
                              type: string
                            latitude:
                              type: string
                            longitude:
                              type: string
                            provider:
                              type: string
                            host:
                              type: string
                          required:
                          - ip
                          - country
                          - city
                          - latitude
                          - longitude
                          - provider
                      required:
                      - id
                      - type
                      - attributes
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                      last:
                        type: string
                      prev:
                        nullable: true
                      next:
                        type: string
                        nullable: true
                    required:
                    - first
                    - last
                    - prev
                    - next
                required:
                - data
                - links
              example:
                data:
                - id: '2866'
                  type: geolocation
                  attributes:
                    ip: 65.57.113.24
                    host: google.com
                    country: Slovakia (Slovak Republic)
                    city: Homenickmouth
                    latitude: "-83.82352998393614"
                    longitude: '148.4892175494342'
                    provider: IPSTACK
                - id: '2867'
                  type: geolocation
                  attributes:
                    ip: 54.190.128.218
                    host: google.com
                    country: United States Minor Outlying Islands
                    city: Cheyenneburgh
                    latitude: '41.94736681298985'
                    longitude: '173.3978671038218'
                    provider: IPSTACK
                - id: '2868'
                  type: geolocation
                  attributes:
                    ip: 100.249.233.110
                    host: google.com
                    country: Christmas Island
                    city: Bobbychester
                    latitude: "-37.69072113472811"
                    longitude: "-144.1909128364867"
                    provider: IPSTACK
                - id: '2869'
                  type: geolocation
                  attributes:
                    ip: 185.116.213.115
                    host: google.com
                    country: El Salvador
                    city: Lake Yong
                    latitude: "-83.20119308750726"
                    longitude: "-32.94703349723451"
                    provider: IPSTACK
                - id: '2870'
                  type: geolocation
                  attributes:
                    ip: 163.104.124.60
                    host: google.com
                    country: Burkina Faso
                    city: Bayermouth
                    latitude: "-13.70264294337002"
                    longitude: "-97.02559565144016"
                    provider: IPSTACK
                links:
                  first: "/api/v1/geolocations?ip_or_host=google.com&page%5Bpage%5D=1&page%5Blimit%5D=5"
                  last: "/api/v1/geolocations?ip_or_host=google.com&page%5Bpage%5D=2&page%5Blimit%5D=5"
                  prev:
                  next: "/api/v1/geolocations?ip_or_host=google.com&page%5Bpage%5D=2&page%5Blimit%5D=5"
        '400':
          description: returns 400 bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                      required:
                      - message
                required:
                - errors
              example:
                errors:
                - message: Query parameter is required (should be IP or Host)
    post:
      summary: create
      tags:
      - API::V1::Geolocation
      responses:
        '201':
          description: returns success and creates new geolocation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          ip:
                            type: string
                          country:
                            type: string
                          city:
                            type: string
                          latitude:
                            type: string
                          longitude:
                            type: string
                          provider:
                            nullable: true
                            type: string
                          host:
                            type: string
                        required:
                        - ip
                        - country
                        - city
                        - latitude
                        - longitude
                        - provider
                    required:
                    - id
                    - type
                    - attributes
                required:
                - data
              example:
                data:
                  id: '2844'
                  type: geolocation
                  attributes:
                    ip: 1.190.139.201
                    country: United States
                    city: Chicago
                    latitude: '10.0'
                    longitude: '11.1'
                    provider: IPSTACK
                    host: 1.190.139.201
        '400':
          description: returns unprocessable entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        ip:
                          type: array
                          items:
                            type: string
                        country:
                          type: array
                          items:
                            type: string
                        city:
                          type: array
                          items:
                            type: string
                        latitude:
                          type: array
                          items:
                            type: string
                        longitude:
                          type: array
                          items:
                            type: string
                      required:
                      - ip
                required:
                - errors
              example:
                errors:
                - ip:
                  - must be a valid IPv4 or IPv6 address
                  country:
                  - can't be blank
                  city:
                  - can't be blank
                  latitude:
                  - can't be blank
                  longitude:
                  - can't be blank
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                geolocation:
                  type: object
                  properties:
                    ip:
                      type: string
                    country:
                      type: string
                    city:
                      type: string
                    latitude:
                      type: string
                    longitude:
                      type: string
                    ip_or_host:
                      type: string
              required:
              - geolocation
            example:
              geolocation:
                ip: 80.104.110.90
                country: Poland
                city: Pollichburgh
                latitude: '22.27435572213743'
                longitude: '134.48079282443842'
                ip_or_host: 1.190.139.201
  "/api/v1/geolocations/{id}":
    delete:
      summary: destroy
      tags:
      - API::V1::Geolocation
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 2886
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties: {}
            example: {}
      responses:
        '204':
          description: returns no content and destroys geolocation
        '404':
          description: returns 404 not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                      required:
                      - message
                required:
                - errors
              example:
                errors:
                - message: Resource not found
    get:
      summary: show
      tags:
      - API::V1::Geolocation
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 2845
      responses:
        '200':
          description: returns successfully single resource
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          ip:
                            type: string
                          country:
                            type: string
                          city:
                            type: string
                          latitude:
                            type: string
                          longitude:
                            type: string
                          provider:
                            type: string
                          host:
                            type: string
                        required:
                        - ip
                        - country
                        - city
                        - latitude
                        - longitude
                        - provider
                    required:
                    - id
                    - type
                    - attributes
                required:
                - data
              example:
                data:
                  id: '2845'
                  type: geolocation
                  attributes:
                    ip: 129.97.171.140
                    country: Senegal
                    city: Wildermanburgh
                    latitude: '63.06380957762468'
                    longitude: "-15.63706482548337"
                    provider: IPSTACK
                    host: http://waters.test/venessa
        '404':
          description: returns 404 not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                      required:
                      - message
                required:
                - errors
              example:
                errors:
                - message: Resource not found
